name: Run terraform plan and upload artifact

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS access key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS secret key'
        required: true
        
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Create Terraform Plan Artifact for Apply'
      run: |
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        terraform init
        terraform plan -out src/tfplan

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: TerraformPlan
        path: src/tfplan
        retention-days: 1
