name: Run terraform plan and upload artifact

on:
  pull_request:
    types:
      - opened

jobs:
  terraform:
    name: Terraform
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2

    - name: 'Create Terraform Plan Artifact for Apply'
      run: |
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        terraform init
        terraform plan -out dev/tfplan

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: TerraformPlan
        path: dev/tfplan
        retention-days: 1
